version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_transcribe_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

