
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_transcribe_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rq_worker
    depends_on:
      - redis
    command: python worker.py
    restart: unless-stopped



